spring.application.name=smartstudy-backend

# Server
server.port=8080

# ===============================
# PostgreSQL Database Config
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/smartstudy_ai
spring.datasource.username=postgres
spring.datasource.password=Niket1@*#
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT config
jwt.secret=change_this_to_a_long_random_secret_please
jwt.expirationMs=3600000   
app.uploads-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
gemini.api.key=AIzaSyAhmN4mEfK9RRU4lxoxC8p15rQdOTKoLgA

cloudinary.cloud-name=duuqobpvr
cloudinary.api-key=768587661318697
cloudinary.api-secret=iew4GSYRFVQUl4RToVkyaSqc5iU